import io
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.lib.utils import ImageReader
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, ListFlowable, ListItem, Image as RLImage, PageBreak

ORANGE = colors.HexColor("#FF5F15")
DARK = colors.HexColor("#0A0A0A")


def _styled_table(rows: list, col_widths: list, extra_style: list = None) -> Table:
    t = Table(rows, colWidths=col_widths)
    style = [
        ("BACKGROUND", (0, 0), (-1, 0), DARK),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]
    t.setStyle(TableStyle(style + (extra_style or [])))
    return t


def _styles() -> dict:
    ss = getSampleStyleSheet()
    return {
        "h1": ParagraphStyle("h1", parent=ss["Heading1"], textColor=DARK, fontSize=18),
        "h2": ParagraphStyle("h2", parent=ss["Heading2"], textColor=ORANGE, fontSize=12, spaceBefore=14),
        "body": ParagraphStyle("body", parent=ss["BodyText"], fontSize=9.5, leading=13),
        "small": ParagraphStyle("small", parent=ss["BodyText"], fontSize=8, textColor=colors.grey),
    }


def _header(job: dict, st: dict) -> list:
    return [
        Paragraph("TMAIT — Traffic Management Plan", st["h1"]),
        Paragraph("Generated by A.T.O.M | Grounded in BC TMM 2020 (Traffic Management Manual for Work on Roadways)", st["small"]),
        Spacer(1, 8),
        Paragraph(f"<b>Job:</b> {job.get('title', '')} &nbsp;&nbsp; <b>Status:</b> {job.get('status', '').upper()} &nbsp;&nbsp; <b>Model:</b> {job.get('model_used', '')}", st["body"]),
        Paragraph(f"<b>Location:</b> {job.get('location', '')}", st["body"]),
    ]


def _text_section(title: str, text, st: dict) -> list:
    if not text:
        return []
    return [Paragraph(title, st["h2"]), Paragraph(str(text).replace("\n", "<br/>"), st["body"])]


def _signage_section(plan: dict, st: dict) -> list:
    signs = plan.get("signage_schedule") or []
    if not signs:
        return []
    rows = [["Sign", "Location", "Spacing", "Notes"]] + [
        [Paragraph(str(s.get(k, "")), st["body"]) for k in ("sign", "location", "spacing_m", "notes")] for s in signs
    ]
    return [Paragraph("6. Signage Schedule", st["h2"]),
            _styled_table(rows, [1.6 * inch, 1.9 * inch, 1.0 * inch, 2.2 * inch])]


def _steps_section(plan: dict, st: dict) -> list:
    steps = plan.get("setup_steps") or []
    if not steps:
        return []
    return [Paragraph("7. Step-by-Step Setup", st["h2"]),
            ListFlowable([ListItem(Paragraph(str(s), st["body"])) for s in steps], bulletType="1")]


def _diagram_pages(plan: dict, diagram_pngs: list, st: dict) -> list:
    if not diagram_pngs:
        return []
    el = []
    lays = plan.get("layouts") or ([plan["layout"]] if plan.get("layout") else [])
    for idx, png in enumerate(diagram_pngs):
        el.append(PageBreak())
        el.append(Paragraph(f"Traffic Control Layout — TMM 2020 Schematic (Sheet TC-{idx + 1} of {len(diagram_pngs)})", st["h2"]))
        ir = ImageReader(io.BytesIO(png))
        iw, ih = ir.getSize()
        ratio = min(7.0 * inch / iw, 8.3 * inch / ih)
        el.append(RLImage(io.BytesIO(png), width=iw * ratio, height=ih * ratio))
        if idx < len(lays) and (lays[idx] or {}).get("notes"):
            el.append(Paragraph(f"NOTE: {lays[idx]['notes']}", st["small"]))
    el.append(PageBreak())
    return el


def _citations_section(plan: dict, st: dict) -> list:
    cits = plan.get("tmm_citations") or []
    if not cits:
        return []
    return [Paragraph("9. TMM 2020 Compliance Citations", st["h2"])] + [
        Paragraph(f"<b>{c.get('section', '')}</b> — {c.get('requirement', '')}", st["body"]) for c in cits
    ]


def _markers_section(plan: dict, st: dict) -> list:
    feats = plan.get("map_features") or {}
    markers = feats.get("markers") or []
    if not markers:
        return []
    center = feats.get("center") or {}
    rows = [["Type", "Label", "Lat", "Lng"]] + [
        [str(m.get("type", "")), Paragraph(str(m.get("label", "")), st["body"]), f"{m.get('lat', 0):.5f}", f"{m.get('lng', 0):.5f}"] for m in markers
    ]
    return [
        Paragraph("10. Site Diagram Reference (coordinates)", st["h2"]),
        Paragraph(f"Map centre: {center.get('lat', '')}, {center.get('lng', '')} — interactive diagram available in TMAIT workspace.", st["small"]),
        _styled_table(rows, [1.1 * inch, 3.0 * inch, 1.3 * inch, 1.3 * inch]),
    ]


def build_plan_pdf(job: dict, diagram_pngs: list | None = None) -> bytes:
    plan = job.get("plan") or {}
    st = _styles()
    el = _header(job, st)
    el += _text_section("1. Location Summary", plan.get("location_summary"), st)
    el += _text_section("2. Event / Works Type", plan.get("event_type"), st)
    el += _text_section("3. Duration", plan.get("duration"), st)
    el += _text_section("4. Road & Lane Closures", plan.get("road_lane_closures"), st)
    el += _text_section("5. Detours", plan.get("detours"), st)
    el += _signage_section(plan, st)
    el += _steps_section(plan, st)
    el += _text_section("8. Safety Considerations", plan.get("safety_considerations"), st)
    el += _diagram_pages(plan, diagram_pngs, st)
    el += _citations_section(plan, st)
    el += _markers_section(plan, st)
    if job.get("review_feedback"):
        el += [Paragraph("Reviewer Feedback", st["h2"]), Paragraph(str(job["review_feedback"]), st["body"])]

    buf = io.BytesIO()
    SimpleDocTemplate(buf, pagesize=letter, topMargin=0.7 * inch, bottomMargin=0.7 * inch).build(el)
    return buf.getvalue()
