import io
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, ListFlowable, ListItem

ORANGE = colors.HexColor("#FF5F15")
DARK = colors.HexColor("#0A0A0A")


def build_plan_pdf(job: dict) -> bytes:
    plan = job.get("plan") or {}
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=letter, topMargin=0.7 * inch, bottomMargin=0.7 * inch)
    ss = getSampleStyleSheet()
    h1 = ParagraphStyle("h1", parent=ss["Heading1"], textColor=DARK, fontSize=18)
    h2 = ParagraphStyle("h2", parent=ss["Heading2"], textColor=ORANGE, fontSize=12, spaceBefore=14)
    body = ParagraphStyle("body", parent=ss["BodyText"], fontSize=9.5, leading=13)
    small = ParagraphStyle("small", parent=ss["BodyText"], fontSize=8, textColor=colors.grey)

    el = [
        Paragraph("TMAIT — Traffic Management Plan", h1),
        Paragraph("Generated by A.T.O.M | Grounded in BC TMM 2020 (Traffic Management Manual for Work on Roadways)", small),
        Spacer(1, 8),
        Paragraph(f"<b>Job:</b> {job.get('title', '')} &nbsp;&nbsp; <b>Status:</b> {job.get('status', '').upper()} &nbsp;&nbsp; <b>Model:</b> {job.get('model_used', '')}", body),
        Paragraph(f"<b>Location:</b> {job.get('location', '')}", body),
    ]

    def section(title, text):
        if text:
            el.append(Paragraph(title, h2))
            el.append(Paragraph(str(text).replace("\n", "<br/>"), body))

    section("1. Location Summary", plan.get("location_summary"))
    section("2. Event / Works Type", plan.get("event_type"))
    section("3. Duration", plan.get("duration"))
    section("4. Road & Lane Closures", plan.get("road_lane_closures"))
    section("5. Detours", plan.get("detours"))

    signs = plan.get("signage_schedule") or []
    if signs:
        el.append(Paragraph("6. Signage Schedule", h2))
        rows = [["Sign", "Location", "Spacing", "Notes"]] + [
            [Paragraph(str(s.get(k, "")), body) for k in ("sign", "location", "spacing_m", "notes")] for s in signs
        ]
        t = Table(rows, colWidths=[1.6 * inch, 1.9 * inch, 1.0 * inch, 2.2 * inch])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), DARK),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]))
        el.append(t)

    steps = plan.get("setup_steps") or []
    if steps:
        el.append(Paragraph("7. Step-by-Step Setup", h2))
        el.append(ListFlowable([ListItem(Paragraph(str(s), body)) for s in steps], bulletType="1"))

    section("8. Safety Considerations", plan.get("safety_considerations"))

    cits = plan.get("tmm_citations") or []
    if cits:
        el.append(Paragraph("9. TMM 2020 Compliance Citations", h2))
        for c in cits:
            el.append(Paragraph(f"<b>{c.get('section', '')}</b> — {c.get('requirement', '')}", body))

    feats = (plan.get("map_features") or {})
    markers = feats.get("markers") or []
    if markers:
        el.append(Paragraph("10. Site Diagram Reference (coordinates)", h2))
        center = feats.get("center") or {}
        el.append(Paragraph(f"Map centre: {center.get('lat', '')}, {center.get('lng', '')} — interactive diagram available in TMAIT workspace.", small))
        rows = [["Type", "Label", "Lat", "Lng"]] + [
            [str(m.get("type", "")), Paragraph(str(m.get("label", "")), body), f"{m.get('lat', 0):.5f}", f"{m.get('lng', 0):.5f}"] for m in markers
        ]
        t = Table(rows, colWidths=[1.1 * inch, 3.0 * inch, 1.3 * inch, 1.3 * inch])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), DARK),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ]))
        el.append(t)

    if job.get("review_feedback"):
        el.append(Paragraph("Reviewer Feedback", h2))
        el.append(Paragraph(str(job["review_feedback"]), body))

    doc.build(el)
    return buf.getvalue()
