import os
import pytest
import requests

BASE_URL = os.environ['REACT_APP_BACKEND_URL'].rstrip('/') if 'REACT_APP_BACKEND_URL' in os.environ else None

# Fallback: read from frontend/.env
if not BASE_URL:
    from pathlib import Path
    env_path = Path('/app/frontend/.env')
    if env_path.exists():
        for line in env_path.read_text().splitlines():
            if line.startswith('REACT_APP_BACKEND_URL='):
                BASE_URL = line.split('=', 1)[1].strip().strip('"').rstrip('/')
                break

assert BASE_URL, "REACT_APP_BACKEND_URL not configured"

API = f"{BASE_URL}/api"

CREDS = {
    "admin": {"email": "admin@tmait.ca", "password": "Admin@1234"},
    "reviewer": {"email": "reviewer@tmait.ca", "password": "Review@1234"},
    "client": {"email": "client@tmait.ca", "password": "Client@1234"},
}


def _login(role):
    r = requests.post(f"{API}/auth/login", json=CREDS[role], timeout=30)
    r.raise_for_status()
    return r.json()["access_token"]


@pytest.fixture(scope="session")
def base_url():
    return BASE_URL


@pytest.fixture(scope="session")
def api_url():
    return API


@pytest.fixture(scope="session")
def admin_token():
    return _login("admin")


@pytest.fixture(scope="session")
def reviewer_token():
    return _login("reviewer")


@pytest.fixture(scope="session")
def client_token():
    return _login("client")


@pytest.fixture
def admin_client(admin_token):
    s = requests.Session()
    s.headers.update({"Authorization": f"Bearer {admin_token}", "Content-Type": "application/json"})
    return s


@pytest.fixture
def reviewer_client(reviewer_token):
    s = requests.Session()
    s.headers.update({"Authorization": f"Bearer {reviewer_token}", "Content-Type": "application/json"})
    return s


@pytest.fixture
def client_client(client_token):
    s = requests.Session()
    s.headers.update({"Authorization": f"Bearer {client_token}", "Content-Type": "application/json"})
    return s


@pytest.fixture(scope="session")
def existing_job_id():
    """Job pre-generated by main agent (has plan)"""
    from pathlib import Path
    p = Path("/tmp/job_id.txt")
    if p.exists():
        return p.read_text().strip()
    return "67c7cffc-aee6-4b1a-8e0a-272f786f0b8b"
